### ISSUE TITLE
hi, i have got an issue in the bot tutorial pt 2 and can someone fix it?

### ISSUE THREAD

**Issue by ghost** [samennis1/Bot-Tutorial#3]
im stuck at typing node . in powershell, it says C:\Users\Desktop\bot\node_modules\discord.js\src\client\Client.js:544  
      throw new TypeError('CLIENT_MISSING_INTENTS');
      ^

TypeError [CLIENT_MISSING_INTENTS]: Valid intents must be provided for the Client.
    at Client._validateOptions (C:\Users\Desktop\Bot\node_modules\discord.js\src\client\Client.js:544:13)
    at new Client (C:\Users\Desktop\bot\node_modules\discord.js\src\cli    at Object.<anonymous> (C:\Users\Desktop\bot\index.js:3:13)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1147:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)   
    at node:internal/main/run_main_module:17:47 {
  [Symbol(code)]: 'CLIENT_MISSING_INTENTS'
}

Node.js v17.0.1
can someone tell me the way to solve it?

**Comment by ModernAesthetics** [comment]
I'm having the same issue

**Comment by nkgautam** [comment]
me too

**Comment by PRO10MIXALIS** [comment]
me too
